name: window_watcher
description: Dart/Flutter package for working with visible windows.
version: 0.0.3
repository: https://github.com/Vonarian/window_watcher
issue_tracker: https://github.com/Vonarian/window_watcher/issues

environment:
  sdk: '>=3.0.6'

platforms:
  windows:

dependencies:
  win32: ^5.0.5
  ffi: ^2.0.1

dev_dependencies:
  lints: ^2.1.1
