name: window_watcher
description: Dart/Flutter package for getting information about windows.
version: 0.0.1
homepage: https://github.com/Vonarian/window_watcher

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  win32: ^3.1.1
  ffi: ^2.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
